# Generated by Django 2.2.13 on 2022-01-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planet_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLONDE', 'BLONDE'), ('BALD', 'BALD'), ('WHITE', 'WHITE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], max_length=32),
        ),
    ]
