# Generated by Django 2.2.13 on 2022-01-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220120_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('bald', 'BALD'), ('black', 'BLACK'), ('white', 'WHITE'), ('brown', 'BROWN'), ('blonde', 'BLONDE'), ('red', 'RED')], max_length=32),
        ),
    ]
