# Generated by Django 2.2.13 on 2022-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220120_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('red', 'RED'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('yellow', 'YELLOW'), ('brown', 'BROWN'), ('unknown', 'UNKNOW')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('white', 'WHITE'), ('red', 'RED'), ('black', 'BLACK'), ('blonde', 'BLONDE'), ('brown', 'BROWN'), ('bald', 'BALD')], max_length=32),
        ),
    ]
