# Generated by Django 2.2.13 on 2022-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220120_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('unknown', 'UNKNOW'), ('yellow', 'YELLOW'), ('black', 'BLACK'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('red', 'RED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('white', 'WHITE'), ('bald', 'BALD'), ('black', 'BLACK'), ('blonde', 'BLONDE'), ('red', 'RED')], max_length=32),
        ),
    ]
