# Generated by Django 2.2.13 on 2022-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220120_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('red', 'RED'), ('yellow', 'YELLOW'), ('unknown', 'UNKNOW'), ('purple', 'PURPLE'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('bald', 'BALD'), ('white', 'WHITE'), ('blonde', 'BLONDE'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
    ]
