# Generated by Django 2.2.13 on 2022-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220120_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('purple', 'PURPLE'), ('unknown', 'UNKNOW'), ('yellow', 'YELLOW'), ('red', 'RED'), ('green', 'GREEN'), ('white', 'WHITE'), ('black', 'BLACK'), ('brown', 'BROWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('bald', 'BALD'), ('blonde', 'BLONDE'), ('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK'), ('brown', 'BROWN')], max_length=32),
        ),
    ]
