# Generated by Django 2.2.13 on 2022-01-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220120_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('unknown', 'UNKNOW'), ('brown', 'BROWN'), ('black', 'BLACK'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('red', 'RED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('white', 'WHITE'), ('black', 'BLACK'), ('bald', 'BALD'), ('red', 'RED'), ('blonde', 'BLONDE')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
