# Generated by Django 2.2.13 on 2022-01-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220120_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('white', 'WHITE'), ('bald', 'BALD'), ('blonde', 'BLONDE'), ('red', 'RED'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('red', 'RED'), ('brown', 'BROWN'), ('black', 'BLACK'), ('unknown', 'UNKNOW'), ('purple', 'PURPLE'), ('green', 'GREEN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('white', 'WHITE'), ('bald', 'BALD'), ('blonde', 'BLONDE'), ('red', 'RED'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('red', 'RED'), ('brown', 'BROWN'), ('black', 'BLACK'), ('unknown', 'UNKNOW'), ('purple', 'PURPLE'), ('green', 'GREEN')], max_length=32),
        ),
    ]
