# Generated by Django 2.2.13 on 2022-01-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220120_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('blonde', 'BLONDE'), ('black', 'BLACK'), ('bald', 'BALD'), ('white', 'WHITE'), ('brown', 'BROWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='home_world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films_character', to='app.Planet'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('red', 'RED'), ('purple', 'PURPLE'), ('black', 'BLACK'), ('green', 'GREEN'), ('unknown', 'UNKNOW'), ('brown', 'BROWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('blonde', 'BLONDE'), ('black', 'BLACK'), ('bald', 'BALD'), ('white', 'WHITE'), ('brown', 'BROWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('red', 'RED'), ('purple', 'PURPLE'), ('black', 'BLACK'), ('green', 'GREEN'), ('unknown', 'UNKNOW'), ('brown', 'BROWN')], max_length=32),
        ),
    ]
