# Generated by Django 2.2.13 on 2022-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220120_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='films',
        ),
        migrations.RemoveField(
            model_name='character',
            name='home_world',
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('black', 'BLACK'), ('bald', 'BALD'), ('brown', 'BROWN'), ('blonde', 'BLONDE'), ('white', 'WHITE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('black', 'BLACK'), ('brown', 'BROWN'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('unknown', 'UNKNOW'), ('purple', 'PURPLE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('black', 'BLACK'), ('bald', 'BALD'), ('brown', 'BROWN'), ('blonde', 'BLONDE'), ('white', 'WHITE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('black', 'BLACK'), ('brown', 'BROWN'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('unknown', 'UNKNOW'), ('purple', 'PURPLE')], max_length=32),
        ),
    ]
