# Generated by Django 2.2.13 on 2022-01-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220120_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('bald', 'BALD'), ('red', 'RED'), ('blonde', 'BLONDE'), ('white', 'WHITE'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('purple', 'PURPLE'), ('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('brown', 'BROWN'), ('black', 'BLACK'), ('unknown', 'UNKNOW')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('bald', 'BALD'), ('red', 'RED'), ('blonde', 'BLONDE'), ('white', 'WHITE'), ('brown', 'BROWN'), ('black', 'BLACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('purple', 'PURPLE'), ('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('brown', 'BROWN'), ('black', 'BLACK'), ('unknown', 'UNKNOW')], max_length=32),
        ),
    ]
