# Generated by Django 2.2.13 on 2022-01-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220120_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='films_character', to='app.Film'),
        ),
        migrations.AddField(
            model_name='character',
            name='home_world',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='films_character', to='app.Planet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('white', 'WHITE'), ('black', 'BLACK'), ('bald', 'BALD'), ('red', 'RED'), ('blonde', 'BLONDE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('black', 'BLACK'), ('purple', 'PURPLE'), ('green', 'GREEN'), ('red', 'RED'), ('unknown', 'UNKNOW'), ('yellow', 'YELLOW')], max_length=32),
        ),
    ]
