# Generated by Django 2.2.13 on 2022-01-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220120_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='home_world',
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('black', 'BLACK'), ('bald', 'BALD'), ('white', 'WHITE'), ('red', 'RED'), ('blonde', 'BLONDE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('purple', 'PURPLE'), ('black', 'BLACK'), ('green', 'GREEN'), ('red', 'RED'), ('yellow', 'YELLOW'), ('unknown', 'UNKNOW')], max_length=32),
        ),
    ]
