# Generated by Django 2.2.13 on 2022-01-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220121_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('green', 'GREEN'), ('black', 'BLACK'), ('blue', 'BLUE'), ('white', 'WHITE'), ('purple', 'PURPLE'), ('unknown', 'UNKNOWN'), ('yellow', 'YELLOW'), ('red', 'RED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('hermaphrodite', 'Hermaphrodite'), ('n/a', 'N/A')], max_length=64),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('blonde', 'BLONDE'), ('black', 'BLACK'), ('white', 'WHITE'), ('bald', 'BALD'), ('none', 'NONE'), ('red', 'RED')], max_length=32),
        ),
    ]
