# Generated by Django 2.2.13 on 2022-01-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220122_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('brown', 'BROWN'), ('black', 'BLACK'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('blue', 'BLUE'), ('white', 'WHITE'), ('red', 'RED'), ('unknown', 'UNKNOWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('none', 'NONE'), ('black', 'BLACK'), ('blonde', 'BLONDE'), ('bald', 'BALD'), ('white', 'WHITE'), ('red', 'RED')], max_length=32),
        ),
    ]
