# Generated by Django 2.2.13 on 2022-01-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220122_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('unknown', 'UNKNOWN'), ('red', 'RED'), ('brown', 'BROWN'), ('blue', 'BLUE'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('purple', 'PURPLE'), ('white', 'WHITE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('none', 'NONE'), ('red', 'RED'), ('brown', 'BROWN'), ('bald', 'BALD'), ('blonde', 'BLONDE'), ('white', 'WHITE')], max_length=32),
        ),
    ]
