# Generated by Django 2.2.13 on 2022-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220122_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('brown', 'BROWN'), ('green', 'GREEN'), ('white', 'WHITE'), ('purple', 'PURPLE'), ('blue', 'BLUE'), ('red', 'RED'), ('unknown', 'UNKNOWN'), ('black', 'BLACK'), ('yellow', 'YELLOW')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('none', 'NONE'), ('brown', 'BROWN'), ('white', 'WHITE'), ('red', 'RED'), ('bald', 'BALD'), ('blonde', 'BLONDE'), ('black', 'BLACK')], max_length=32),
        ),
    ]
