# Generated by Django 2.2.13 on 2022-01-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220122_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('brown', 'BROWN'), ('unknown', 'UNKNOWN'), ('red', 'RED'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('white', 'WHITE'), ('black', 'BLACK'), ('blue', 'BLUE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('blonde', 'BLONDE'), ('bald', 'BALD'), ('none', 'NONE'), ('brown', 'BROWN'), ('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK')], max_length=32),
        ),
    ]
