# Generated by Django 2.2.13 on 2022-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220122_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='films',
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('purple', 'PURPLE'), ('yellow', 'YELLOW'), ('red', 'RED'), ('blue', 'BLUE'), ('black', 'BLACK'), ('unknown', 'UNKNOWN'), ('brown', 'BROWN'), ('white', 'WHITE'), ('green', 'GREEN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('black', 'BLACK'), ('bald', 'BALD'), ('brown', 'BROWN'), ('blonde', 'BLONDE'), ('white', 'WHITE'), ('none', 'NONE')], max_length=32),
        ),
    ]
