# Generated by Django 2.2.13 on 2022-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220122_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='films_character', to='app.Film'),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('unknown', 'UNKNOWN'), ('purple', 'PURPLE'), ('blue', 'BLUE'), ('black', 'BLACK'), ('green', 'GREEN'), ('red', 'RED'), ('brown', 'BROWN'), ('white', 'WHITE'), ('yellow', 'YELLOW')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('blonde', 'BLONDE'), ('black', 'BLACK'), ('red', 'RED'), ('bald', 'BALD'), ('brown', 'BROWN'), ('white', 'WHITE'), ('none', 'NONE')], max_length=32),
        ),
    ]
