# Generated by Django 2.2.13 on 2022-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220122_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('yellow', 'YELLOW'), ('red', 'RED'), ('blue', 'BLUE'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('unknown', 'UNKNOWN'), ('white', 'WHITE'), ('black', 'BLACK'), ('brown', 'BROWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('bald', 'BALD'), ('white', 'WHITE'), ('black', 'BLACK'), ('brown', 'BROWN'), ('none', 'NONE'), ('blonde', 'BLONDE')], max_length=32),
        ),
    ]
